# Generated by Django 3.2 on 2024-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Coordinates', models.CharField(max_length=100)),
                ('image', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_range_low', models.CharField(max_length=100)),
                ('Address_range_igh', models.CharField(max_length=100)),
                ('severity', models.FloatField()),
                ('images', models.JSONField()),
            ],
        ),
    ]
