# Generated by Django 3.2 on 2024-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='Address_range_igh',
            new_name='Address_range_high',
        ),
        migrations.AlterField(
            model_name='unit',
            name='images',
            field=models.JSONField(null=True),
        ),
    ]
