# Generated by Django 3.2 on 2024-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='flow_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='radius_m',
            field=models.FloatField(default=0.25),
            preserve_default=False,
        ),
    ]
