# Generated by Django 3.2 on 2024-04-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240407_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='severity',
            field=models.FloatField(null=True),
        ),
    ]
